export * from "./cv.routes";
export * from "./talentProfile.routes";
export * from "./user.routes";
export * from "./employerProfile.routes";
export * from "./auth.router";
export * from "./appliedJobs.routes";
export * from "./jobPosting.routes";
export * from "./favoriteJobs.routes";
export * from "./logout.routes";
