import type {
  CreateUserInputSchema,
  ReqUserSchema,
  UpdateUserSchema,
  UserResponseSchema,
  UserSchema,
} from "@/validator/user.validator";
import type { z } from "zod";
import type { AccessAndRefreshTokens } from "./token.types.";
export enum UserRole {
  ADMIN = "admin",
  TALENT = "talent",
  RECRUITER = "recruiter",
}

export enum Experience {
  ENTRY_LEVEL = "Entry Level",
  MID_LEVEL = "Mid Level",
  SENIOR_LEVEL = "Senior Level",
}

export enum Gender {
  MALE = "male",
  FEMALE = "female",
}
export enum Country {
  ALGERIA = "Algeria",
  ANGOLA = "Angola",
  BENIN = "Benin",
  BOTSWANA = "Botswana",
  BURKINA_FASO = "Burkina Faso",
  BURUNDI = "Burundi",
  CAPE_VERDE = "Cape Verde",
  CAMEROON = "Cameroon",
  CENTRAL_AFRICAN_REPUBLIC = "Central African Republic",
  CHAD = "Chad",
  COMOROS = "Comoros",
  DEMOCRATIC_REPUBLIC_OF_CONGO = "Democratic Republic of the Congo",
  DJIBOUTI = "Djibouti",
  EGYPT = "Egypt",
  EQUATORIAL_GUINEA = "Equatorial Guinea",
  ERITREA = "Eritrea",
  ESWATINI = "Eswatini",
  ETHIOPIA = "Ethiopia",
  GABON = "Gabon",
  GAMBIA = "Gambia",
  GHANA = "Ghana",
  GUINEA = "Guinea",
  GUINEA_BISSAU = "Guinea-Bissau",
  IVORY_COAST = "Ivory Coast",
  KENYA = "Kenya",
  LESOTHO = "Lesotho",
  LIBERIA = "Liberia",
  LIBYA = "Libya",
  MADAGASCAR = "Madagascar",
  MALAWI = "Malawi",
  MALI = "Mali",
  MAURITANIA = "Mauritania",
  MAURITIUS = "Mauritius",
  MOROCCO = "Morocco",
  MOZAMBIQUE = "Mozambique",
  NAMIBIA = "Namibia",
  NIGER = "Niger",
  NIGERIA = "Nigeria",
  RWANDA = "Rwanda",
  SAO_TOME_AND_PRINCIPE = "São Tomé and Príncipe",
  SENEGAL = "Senegal",
  SEYCHELLES = "Seychelles",
  SIERRA_LEONE = "Sierra Leone",
  SOMALIA = "Somalia",
  SOUTH_AFRICA = "South Africa",
  SOUTH_SUDAN = "South Sudan",
  SUDAN = "Sudan",
  TANZANIA = "Tanzania",
  TOGO = "Togo",
  TUNISIA = "Tunisia",
  UGANDA = "Uganda",
  ZAMBIA = "Zambia",
  ZIMBABWE = "Zimbabwe",
}
export enum Nationality {
  ALGERIA = "Algerian",
  ANGOLA = "Angolan",
  BENIN = "Beninese",
  BOTSWANA = "Motswana",
  BURKINA_FASO = "Burkinabe",
  BURUNDI = "Burundian",
  CAMEROON = "Cameroonian",
  CAPE_VERDE = "Cape Verdean",
  CENTRAL_AFRICAN_REPUBLIC = "Central African",
  CHAD = "Chadian",
  COMOROS = "Comorian",
  CONGO = "Congolese",
  DEMOCRATIC_REPUBLIC_OF_CONGO = "Congolese",
  DJIBOUTI = "Djiboutian",
  EGYPT = "Egyptian",
  EQUATORIAL_GUINEA = "Equatorial Guinean",
  ERITREA = "Eritrean",
  ESWATINI = "Swazi",
  ETHIOPIA = "Ethiopian",
  GABON = "Gabonese",
  GAMBIA = "Gambian",
  GHANA = "Ghanaian",
  GUINEA = "Guinean",
  GUINEA_BISSAU = "Bissau-Guinean",
  IVORY_COAST = "Ivorian",
  KENYA = "Kenyan",
  LESOTHO = "Mosotho",
  LIBERIA = "Liberian",
  LIBYA = "Libyan",
  MADAGASCAR = "Malagasy",
  MALAWI = "Malawian",
  MALI = "Malian",
  MAURITANIA = "Mauritanian",
  MAURITIUS = "Mauritian",
  MOROCCO = "Moroccan",
  MOZAMBIQUE = "Mozambican",
  NAMIBIA = "Namibian",
  NIGER = "Nigerien",
  NIGERIA = "Nigerian",
  RWANDA = "Rwandan",
  SAO_TOME_AND_PRINCIPE = "Santomean",
  SENEGAL = "Senegalese",
  SEYCHELLES = "Seychellois",
  SIERRA_LEONE = "Sierra Leonean",
  SOMALIA = "Somali",
  SOUTH_AFRICA = "South African",
  SOUTH_SUDAN = "South Sudanese",
  SUDAN = "Sudanese",
  TANZANIA = "Tanzanian",
  TOGO = "Togolese",
  TUNISIA = "Tunisian",
  UGANDA = "Ugandan",
  ZAMBIA = "Zambian",
  ZIMBABWE = "Zimbabwean",
}

export type UserType = z.infer<typeof UserSchema>;
export type UserInputType = z.infer<typeof CreateUserInputSchema>;
export type UpdateUserType = z.infer<typeof UpdateUserSchema>;
export type UserResponseType = z.infer<typeof UserResponseSchema>;

export interface UserWithTokens {
  user: UserResponseType;
  tokens: AccessAndRefreshTokens;
}
export type ReqUserType = z.infer<typeof ReqUserSchema>;
